### PR TITLE
Added app functionality

### PR DESCRIPTION
**Pull request by gtabul**

### CODE REVIEW

**Review by LenBekker — APPROVED** [review]
Cool.

**Review by LenBekker — CHANGES_REQUESTED** [review]
Rephrase that, un-cool.

**Comment by gtabul** [comment]
We need to convert our unit tests to Python before we can merge back into Development otherwise our builds will keep failing. Thanks for pointing it out Len.

**Comment by LenBekker** [comment]
No. 

Please 5.

**Review by LenBekker — APPROVED** [review]

**Comment by gtabul** [comment]
@LenBekker Thank you, Len. 

I will name my firstborn after you to honour your lineage.

**Review by Brendon127 — APPROVED** [review]

**Review by u14177553 — APPROVED** [review]
Ye GO FORTH

**Pull request merged**
